name: Snake Game

on:
  # Controlador do tempo que sera fieito a atualização
  schedule:
    - cron: "0 */24 * * *" 

  # Permite executar na lista de Actions
  workflow_dispatch:

 # Regras
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/chekout@v2
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: renanlima2023
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
